[package]
name = "todo_web"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = "0.20.0"
reqwasm = "0.2"
serde = { version = "1.0", featrures = ["derive"] }
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
